//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendBeast.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ability
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int monster_id { get; set; }
        public Nullable<int> hp_mod { get; set; }
        public Nullable<double> strength_mult { get; set; }
        public Nullable<double> toughness_mult { get; set; }
        public Nullable<double> smartness_mult { get; set; }
        public int cooldown { get; set; }
    
        public virtual Monster Monster { get; set; }
    }
}
