//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendBeast.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intruder
    {
        public int id { get; set; }
        public string name { get; set; }
        public int hp_init { get; set; }
        public int strength_init { get; set; }
        public int toughness_init { get; set; }
        public int smartness_init { get; set; }
        public int lvl_min { get; set; }
        public byte[] picture { get; set; }
    }
}
