//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendBeast.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monster()
        {
            this.Abilities = new HashSet<Ability>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int hp_init { get; set; }
        public int strength_init { get; set; }
        public int toughness_init { get; set; }
        public int smartness_init { get; set; }
        public string description { get; set; }
        public string picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ability> Abilities { get; set; }
    }
}
